spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dativus_db
    username: postgres
    password: your_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  # Spring Boot가 토큰을 '만들 때' 사용하는 키
  secret: DativusCapstoneProjectSuperSecretMasterKey2026ForJwtAuthentication
  expiration_time: 3600000 # 60분 (밀리초 단위)